# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255, verbose_name='IP Adresi')),
                ('tcp', models.CommaSeparatedIntegerField(blank=True, max_length=1024, null=True)),
                ('udp', models.CommaSeparatedIntegerField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'verbose_name': 'Alarm',
                'verbose_name_plural': 'Alarmlar',
            },
        ),
        migrations.CreateModel(
            name='AssetList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('tcp', models.CommaSeparatedIntegerField(blank=True, max_length=1024, null=True)),
                ('udp', models.CommaSeparatedIntegerField(blank=True, max_length=1024, null=True)),
                ('definition', models.CharField(blank=True, max_length=255, null=True, verbose_name='A\xe7\u0131klama')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assetlist',
                'verbose_name_plural': 'Assetlistler',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=255, verbose_name='A\xe7\u0131klama')),
            ],
            options={
                'verbose_name': 'Grup',
                'verbose_name_plural': 'Gruplar',
            },
        ),
        migrations.AddField(
            model_name='assetlist',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portscan.Group', verbose_name='Grup'),
        ),
    ]
